services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    user: root
    container_name: live-testing-1
    ports:
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html/backend/storage /var/www/html/backend/bootstrap/cache && php-fpm"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - PHP_IDE_CONFIG=serverName=Docker
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003

    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=live_testing
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=!23qweakM!
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: ../.docker/frontend/Dockerfile
    container_name: live-testing-frontend
    ports:
      - "5173:5173"
    #volumes:
     # - ./frontend:/app

volumes:
  db_data:
