services:
  app:
    build: 
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: live-testing-1
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=live_testing
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=!23qweakM!
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80" 
    volumes:
      - .:/var/www/html  
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - app

volumes:
  db_data: